### ISSUE TITLE
Invisible Divider/Icon

### ISSUE THREAD

**Issue by Laicure** [EthanSK/Menu-Bar-Dock#27]
Any way to remove the invisible dividers between the music and duckstation icon below?
![image](https://github.com/EthanSK/Menu-Bar-Dock/assets/8619566/52ed5d37-91da-41f0-b4ba-6e004acd657e)
another example (between Chrome and Word):
![image](https://github.com/EthanSK/Menu-Bar-Dock/assets/8619566/f01ae57b-cf27-44b3-8d19-3b0c5edb02af)
just now (I'm on an online meeting with microphone):
![image](https://github.com/EthanSK/Menu-Bar-Dock/assets/8619566/52007065-d521-4ae8-9d47-f77cbd907ec6)

I can actually move it when I'm doing a cmd+clickdrag but no way to remove it.
No weird apps installed on my end.
![image](https://github.com/EthanSK/Menu-Bar-Dock/assets/8619566/c0356dfe-e0ae-40da-8a4f-43a6483670a7)

here are my settings:
![image](https://github.com/EthanSK/Menu-Bar-Dock/assets/8619566/b0b0b7f6-c7b9-4ca4-a882-4531e5b1e17f)

**Comment by Laicure** [comment]
It's still there. The hidden dividers :(
https://github.com/EthanSK/Menu-Bar-Dock/assets/8619566/2eeb8fb6-328c-423f-837b-b7e6049cc322

**Comment by droplinxuser** [comment]
I have a similar gap after the Dropbox icon, too.

**Comment by andylundqvist** [comment]
Yes, seems to be broken, these gaps just appear randomly. Also the sorting is broken in Sonoma. No update to this app for a LONG time now. Are there any alternatives? I love the idea but it's buggy and probably abandoned...

**Comment by Laicure** [comment]
> Yes, seems to be broken, these gaps just appear randomly. Also the sorting is broken in Sonoma. No update to this app for a LONG time now. Are there any alternatives? I love the idea but it's buggy and probably abandoned...

I'm actively seeking an alternative to this app but haven't found any too. :(
Currently, I'm just managing all windows via Mission Control, ugh.

**Comment by andylundqvist** [comment]
> I'm actively seeking an alternative to this app but haven't found any too. :( Currently, I'm just managing all windows via Mission Control, ugh.

I still use Menu Bar Dock despite the bugs, together with Hidden Bar and regular cmd-tab.

Pinging @EthanSK - I know you haven't updated in a long, long time but do you have any plans to fix the software for the future? Such as the random sorting bug (Sort order: Consistent does not work) and the randomly appearing empty spaces? I have a feeling there are a bunch of people who love this app and as far as I know the only app that replaces the dock. Truly one of a kind.

**Comment by wolveix** [comment]
Just opened a PR to address this, hoping that Ethan has the time to review and merge :) 

Per the comments in the source code, the spacing is caused by not wanting to hide buttons entirely as it breaks the user-specified sorting (if you CMD + drag the buttons around). The `Preserve app order` user preference in my pull request disables this. I don't personally CMD + drag buttons around whatsoever, so this was a non-issue for me personally.

@andylundqvist I haven't personally been able to reproduce any sorting issues. I add all of my regular apps under the "Regular Apps" user preference section, and this maintains the app order for me
