### ISSUE TITLE
Issue: Menu Bar Dock Creates Many "Blank" Icons with Bartender 4

### ISSUE THREAD

**Issue by shouyang** [EthanSK/Menu-Bar-Dock#7]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/16977648/114348703-1e098380-9b24-11eb-8b36-8827156821b0.png">

Context: I'm experimenting with layouts between this and bartender 4. Ideally I'd like to set an area to store the dock icons on the right either hidden in the bartender drawer or just on the menu bar.

Issue: After using menu bar dock for a while, I noticed that these "spacer" icons are appearing after closing apps. This happens both when I set bartender 4 to put all new icons on the menu-bar or in its hidden drawer.

Steps to reproduce:
- Open menu-bar-dock
- Open a bunch of applications (like MS office)
- Close all of the applications
- Open a few new applications
- Observe that the new applications have oddly spaced icons.

<img width="981" alt="image" src="https://user-images.githubusercontent.com/16977648/114348562-f4e8f300-9b23-11eb-939c-ef41b625d830.png">

<img width="616" alt="image" src="https://user-images.githubusercontent.com/16977648/114348828-4db88b80-9b24-11eb-9b19-ad83c9952dfc.png">

**Comment by EthanSK** [comment]
Please can you try with the latest update and see if it still causes you issues+

**Comment by milesmcclane** [comment]
Actually I have had this issue, and I can confirm it still exists. 

As of now I am just using MenuBarDock with a couple of apps using the new regular apps feature. I have the number of running apps set to zero, as thats what I want for my set up. 
However, if i increase that then there are issues arrising which are very bizarre. 
Blank spaces can appear at any point over the menu bar, even between seemingly unrelated standard dock icons. No matter whether ‘consistent’ is ticked or not, the apps are not remaining in a consistent place, and randomly change depending on which is the active app. 
I’m using Bartender 4 as the op is too.

**Comment by EthanSK** [comment]
The blank spaces is a known issue even when using MBD normally, unfortunately I can't think of a good workaround. I left a comment in the code explaining why, but here it is for your convenience:

KNOWN ISSUE: After opening some apps, then closing some, there will be a gap of
empty space where the items of length 0 are (because they are trying to be hidden).
There is nothing currently we can do to stop this, the alternative is using statusItem.isVisible = false,
but then that causes the items to not restore to their correct, user-defined positions on the menu
bar...It is therefore recommended to only drag N apps to the right, where N is a
relatively small number that is ideally less than the number of apps you would tend
to have running at any given time

**Comment by milesmcclane** [comment]
Ah ok. Thanks for the explanation.

No, turning off or leaving on the hide active app option doesnt change anything. 

I’m not the OP though and as I said, 'im happy with the afore metioned change and it’s how i'll be using the app. This works perfectly!

**Comment by shouyang** [comment]
Cool, thanks for looking into this!
