### ISSUE TITLE
Right click on a menu bar item doesn’t work in Sidecar with an Apple Pencil (Control-click with a keyboard and mouse doesn’t work either)

### ISSUE THREAD

**Issue by Gris-Dos** [EthanSK/Menu-Bar-Dock#8]
In Sidecar on an iPad with an Apple Pencil a right click is done by pressing on the ^ symbol in the sidebar, while tapping with the pencil. But it doesn’t work on the app icons from the Menu Bar Dock in the menu bar, making the app preferences inaccessible!

**Comment by Gris-Dos** [comment]
I’ve just tested with a keyboard and mouse: it doesn’t work either! You can’t control-click on an app icon in the menu bar to open the Menu Bar Dock menu. (By the way, and sorry if you already knew that, control-click is the historical way of right-clicking on the Mac, back when Apple mice had only one button)

**Comment by wolveix** [comment]
This is how the macOS menu bar behaves, and has nothing to do with this project (option-clicking menu bar buttons does nothing).

It would be nice to have a workaround for this, though. My immediate suggestion would be to change the left-click action to instead open the menu rather than immediately open the application, though that's a core flow change for this application
